version: "3.7"

services:
  traffichandler_app:
    image: errfire/traffichandler:0.5.0-Beta
    container_name: traffichandler_app
    ports:
      - 443:443
      - 80:80
    environment:
      - TZ=Europa/Berlin
    volumes:
      - ./data/traffic_handler/logs:/opt/traffic_handler/logs
      - ./data/traffic_handler/data:/opt/traffic_handler/data
      - ./data/traffic_handler/conf:/opt/traffic_handler/conf
      - ./data/traffic_handler/database:/opt/traffic_handler/system/de.err.traffichandler/instance