version: "3.7"

services:
  traffichandler_app:
    image: errfire/traffichandler:latest
    container_name: traffichandler_app
    ports:
      - 443:443
    environment:
      - TZ=Amsterdam/Berlin
    volumes:
      - ./data/traffic_handler/logs:/opt/traffic_handler/logs
      - ./data/traffic_handler/data:/opt/traffic_handler/data
      - ./data/traffic_handler/conf:/opt/traffic_handler/conf
      - ./data/traffic_handler/database:/opt/traffic_handler/system/de.err.traffichandler/instance
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost/"]
      interval: 60s
      retries: 3
      start_period: 60s
      timeout: 10s